pipeline {
    agent {
        label 'AGENT-1'
    }
    options{
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }

    parameters {

        choice(name: 'ACTION', choices: ['apply', 'destroy'], description: 'select action')
    }
    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds-rakesh'){
                sh """
                cd 00-vpc
                terraform init -reconfigure
                terraform plan -out=tfplan
                """
                }
            }
        }
        stage('Apply or Destroy') {
            input{
                message "should we continue ${params.ACTION}"
                ok "Yes, we should"
            }
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds-rakesh'){
                sh """
                    cd 00-vpc
                        if [ ${params.ACTION} == 'apply' ]
                        then
                            terraform apply -auto-approve tfplan
                        elif [ ${params.ACTION} == 'destroy' ]
                        then
                            terraform destroy -auto-approve
                        fi
                """
                    }
                }
            }
            stage ('Triggers SG') {
                steps{
                    build job: '10-sg', parameters: [string(name: 'ACTION', value: "apply")], wait: false
                }
            }
    }
    post {
        always {
            echo "this section runs always"
            deleteDir()
        }
        success{
            echo "this section runs when pipeline success"
        }
        failure{
            echo "this section runs when pipeline failure"
        }
    }
}
